routes:
  /democracys-top-ten/:
    template: page-demten
    data: page.democracys-top-ten
  /organizations/:
    template: page-about
    data: page.organizations
  /about/:
    template: page-about
    data: page.about-mr-pillsbury
  #/search/:
  #  template: page-search
  #  data: page.search
  /membership/: members/membership
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /:
    data: page.home
    template: home

  /archive/:
    template: archive

collections:
  # /updates/:
  #   permalink: /{slug}/
  #   filter: tag:updates
  #   template: tag
  /blog/:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/